FROM outstand/phoenix:1.4.17-alpine
LABEL maintainer="Ryan Schlesinger <ryan@outstand.com>"

RUN apk add --no-cache \
      xvfb \
      xdpyinfo \
      harfbuzz \
      nss \
      freetype \
      ttf-freefont \
      chromium \
      chromium-chromedriver
